export enum COMMON_EVENT {
  SHOW_SIDER_POPUP = 'SHOW_SIDER_POPUP',
  SHOW_SELECT_PERPETUAL_POPUP = 'SHOW_SELECT_PERPETUAL_POPUP',
  SHOW_CHANGE_TARGET_LEVERAGE_POPUP = 'SHOW_CHANGE_TARGET_LEVERAGE_POPUP',
  SHOW_SELECT_WALLET_POPUP = 'SHOW_SELECT_WALLET_POPUP',
  CHANGE_POOL_LIQUIDITY = 'CHANGE_POOL_LIQUIDITY',
  SHOW_VAULT_ASSET_POPUP = 'SHOW_VAULT_ASSET_POPUP'
}
